### ISSUE TITLE
Leaderboards command to print all leaderboards

### ISSUE THREAD

**Issue by michael-robbins** [emojirades/emojirades#188]
It'd be nice if '@emojirade leaderboards' printed all the leaderboards available

**Comment by michael-robbins** [comment]
Something like:

1. Weekly
2. Monthly
3. Overall

Possibly

**Comment by phelios** [comment]
so, any preference?

Thinking that if it's simpler and cleaner if default only show Weekly. And people can say "leaderboard all" to show all.

**Comment by michael-robbins** [comment]
Yep, I'm happy to rejig the command to default to 'weekly' and then users can choose other ones.

'alltime', 'weekly' and 'monthly' sound good to me, with the default being weekly!
