### ISSUE TITLE
Send reminder to users to supply rade

### ISSUE THREAD

**Issue by mark-sinclair-carsales** [emojirades/emojirades#265]
Send msg to users to prompt them to send rade & start game if not done in 12/24 hours. Ideally not over the weekend.

**Comment by michael-robbins** [comment]
This kinda leans on a 'scheduling capability' or concept of time outside of the 'event driven framework' the game currently runs off (eg. we react to an event from slack, eg a guess).

We will need to build in some sort of 'timer' concept that runs inside the slack bot, and each game and register events with the timer that the timer will execute (eg. every 5 minutes, post a message to the game channel)

**Comment by michael-robbins** [comment]
Maybe it could look like a cron string, combined with a new 'event' object we register to the scheduler/timer.
