### ISSUE TITLE
Monthly Ladder System

### ISSUE THREAD

**Issue by starfallz** [emojirades/emojirades#88]
With new @ladderboard command we should be able to view the current season's scores. It should contain each players' names and diamonds to indicate the number of seasonal wins they have obtained. This should be sorted by the number of wins in the current season (not on the number of diamonds).

Seasons can be monthly based to start with. The winner would be calculated on the first day of each month and potentially announced automatically in the channel on the first day of the month.

With new @ladderboard [playername] we should be able to view a more detailed view of the player's profile. It should contain the player's current month score, total score (from @leaderboard), and their diamonds with their corresponding monthYear.

so eg:
@ladderboard

====Current Season [Jan19]====
1. David Mitchell :gem: [31]
2. sufendy [23]
3. Michael Robbins [11]
.
.

@ladderboard sufendy

====Sufendy's Achievements====
Current: 23
Lifetime: 155
:gem:: 3 [Feb19, Jul19, Feb20]

**Comment by michael-robbins** [comment]
The only error I can see here is me being on 11 points 😂

**Comment by michael-robbins** [comment]
Outstanding features once #168 gets merged in:
* Ability to query individuals in the leaderboard command
* Detect when a new 'week or month' has rolled over, and calculate/award points?

**Comment by phelios** [comment]
So thinking what's next (+ missing features)
- Show date range of the top of the leaderboard
- Ability to say "weekly n" and show n weeks from today. And for monthly as well.
- Maybe ability to enter a date format and it will show you the week or month leaderboard as of that date.

Looks like I kept going on a different direction from this feature request 😆 . But will consider adding those in as well.

**Comment by michael-robbins** [comment]
OK looks like this is done now, we've weekly and monthly leaderboards in and working!
